questionsDict = {
    "What is the capital of France?": "Paris",
    "What planet is known as the Red Planet?": "Mars",
    "What is 12 * 8?": "96",
    "What is the largest ocean on Earth?": "Pacific",
    "Who created Python?": "Guido van Rossum",
    "What keyword is used to define a function in Python?": "def",
    "What data type stores key-value pairs in Python?": "dictionary",
    "What does CPU stand for?": "Central Processing Unit",
    "How many bits are in one byte?": "8",
    "What is the square root of 144?": "12",
    "What is the largest planet in the Solar System?": "Jupiter",
    "What is the chemical symbol for gold?": "Au",
    "How many continents are there?": "7",
    "What is the capital of Italy?": "Rome",
    "What is 15 squared?": "225",
    "What language is primarily used to style web pages?": "CSS",
    "What does RAM stand for?": "Random Access Memory",
    "What is the freezing point of water in Celsius?": "0",
    "What is the smallest prime number?": "2",
    "What is the capital of Japan?": "Tokyo",
    "Which planet is closest to the Sun?": "Mercury",
    "What is 144 divided by 12?": "12",
    "What Python keyword is used to create a class?": "class",
    "What file extension is commonly used for Python files?": ".py",
    "What does HTML stand for?": "HyperText Markup Language",
    "Which organ pumps blood through the human body?": "Heart",
    "What is the capital of Germany?": "Berlin",
    "What is 9 * 13?": "117",
    "What data type stores True or False values in Python?": "boolean",
    "What function is commonly used to get user input in Python?": "input"
}

indices = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']